---
title: "University Projects Portfolio"
output: html_document
---

<style type="text/css">
.title {
  display: none;
}

#getting-started img {
  margin-right: 10px;
}

</style>

<div class="row" style="padding-top: 30px;">
<div class="col-sm-6">

# **University Projects Portfolio**

This is a compilation of my projects completed in R Studio as a part of my graduate certificate in Data Science at RMIT University. 


## RStudio Projects:

### 1. Weather & Fatality Rates
The first project I worked on looked at open source data from Our World in Data named Fatality Rates in the US Due to Weather Events. The project was based on taking open source data, importing it into RStudio and using wrangling techniques to create a data set suitable for statistical analysis. Techniques used include conversion of data types, pivots to conform to tidy data principles, providing summary statistics, joining new variable lists to data set and data sub-setting.

### 2. Pollution & Hospital Admissions
The second project I worked on used two open source data sets from Kaggle named Hospital Admissions Data Two Year Hospital Admissions and Discharge Data from Hero DMC Heart Institution. The aim of this project was to merge the two data sets to create insight around Hospital Admissions at the DMC Heart Institute in India and pollution levels on corresponding admission dates. New variables were created for analysis, missing values were addressed and outliers were idenfitied. 




</div>
<div class="col-sm-6">


</a>
</div>
